Universe              = vanilla
executable            = run_production.sh
#			process		part	  n_events	alp_mass (GeV) ctau_0
arguments             = tta 		$(ProcId) 10000		2.75		-1
GetEnv                = True
output                = output/$(ClusterId).$(ProcId).out
error                 = error/$(ClusterId).$(ProcId).err
log                   = log/$(ClusterId).log
requirements 	      = (OpSysAndVer =?= "CentOS7")
+JobFlavour           = "longlunch"

queue 100
